CDにRSSフィードの取得を組み込む
ksquadjp/website pull request #46
Opened 2023-03-25 00:50 UTC by umepon0626

2023-03-25 01:38 UTC, komi1230 approved these changes
良さみ

2023-03-26 07:40 UTC, h3y6e requested changes
1点気になる部分がありました、ほかはよさそうです:ok_man:

2023-03-26 07:40 UTC, h3y6e commented on package.json
> +    "build": "run-s build:collect_rss build:astro",
`npm-run-all` は2018年で更新が止まっており、依存関係にあるライブラリに脆弱性が幾つか報告されているので使うのがちょっと憚られる (雑にglob的に書けるのは便利だし、非常に危険というわけではない)

このチームの実行環境は現状macOSのbash or zshな筈で、CI/CDもubuntuのbashなので、`&&`でnpm-scriptsを接続する記法で充分かな?と思います

2023-03-29 11:08 UTC, umepon0626 commented on package.json
> +    "build": "run-s build:collect_rss build:astro",
コメントありがとうございます！
脆弱性は知らなかったです...!モジュール追加するときはこれから気をつけようと思います！

2023-03-30 04:34 UTC, h3y6e approved these changes
🙆‍♂️

2023-04-14 04:44 UTC, merged